import assert from 'node:assert/strict';
import { test } from 'node:test';
import { mkdtemp } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { PersonalMemory } from '../memory/store';
import { ProfileStore } from './profiles';
import { WorkService } from './work';
import { BriefingWorker, dueSlot } from './worker';
const owner = { workspaceId: 'T1', userId: 'U1' };
test('weekday slots use Singapore time and weekends do not schedule', () => {
  assert.equal(dueSlot(new Date('2026-09-14T00:29:00Z')), undefined);
  assert.equal(dueSlot(new Date('2026-09-14T00:30:00Z')), '2026-09-14:08:30');
  assert.equal(dueSlot(new Date('2026-09-14T05:15:00Z')), '2026-09-14:13:00');
  assert.equal(dueSlot(new Date('2026-09-12T00:30:00Z')), undefined);
});
test('overlap and restart send once; failed deliveries remain retryable and opt-out prevents delivery', async () => {
  const dir = await mkdtemp(join(tmpdir(), 'intern-worker-'));
  const profiles = new ProfileStore(join(dir, 'p.json'));
  const work = new WorkService(profiles, new PersonalMemory(join(dir, 'm.json')), { canRead: true, canDeliver: true, async readThread() { return []; } }, async () => undefined);
  await profiles.setSchedule(owner, true);
  let sent = 0, fail = true;
  const deliver = async () => { if (fail) throw new Error('delivery failed'); sent++; };
  const worker = new BriefingWorker(work, deliver, () => new Date('2026-09-14T00:30:00Z'));
  await worker.tick();
  assert.equal((await profiles.get(owner)).jobs.length, 0);
  fail = false;
  await Promise.all([worker.tick(), worker.tick()]);
  assert.equal(sent, 1);
  await new BriefingWorker(work, deliver, () => new Date('2026-09-14T00:30:00Z')).tick();
  assert.equal(sent, 1);
  await profiles.setSchedule(owner, false);
  await new BriefingWorker(work, deliver, () => new Date('2026-09-15T00:30:00Z')).tick();
  assert.equal(sent, 1);
});
test('failed refresh retries within its slot without repeating the warning', async () => {
  const dir = await mkdtemp(join(tmpdir(), 'intern-retry-'));
  const profiles = new ProfileStore(join(dir, 'p.json'));
  await profiles.setSchedule(owner, true);
  await profiles.select(owner, { channelId: 'C1', threadTs: '1726000000.000001', workspaceHost: 'acme.slack.com' });
  let denied = true, reads = 0, sent = 0;
  const work = new WorkService(profiles, new PersonalMemory(join(dir, 'm.json')), { canRead: true, canDeliver: true, async readThread() { reads++; if (denied) throw new Error('temporary'); return [{ threadId: 'C1:1726000000.000001', messageId: '1726000000.000001', authorId: 'U1', text: 'Hello', sentAt: '2024-09-10T20:26:40Z', url: 'https://acme.slack.com/archives/C1/p1726000000000001' }]; } }, async () => undefined);
  let now = new Date('2026-09-14T00:30:00Z');
  const worker = new BriefingWorker(work, async () => { sent++; }, () => now);
  await worker.tick();
  assert.equal(sent, 1);
  assert.equal((await profiles.get(owner)).jobs.includes('2026-09-14:08:30'), false);
  now = new Date('2026-09-14T00:32:00Z');
  await worker.tick();
  assert.equal(sent, 1);
  denied = false;
  now = new Date('2026-09-14T00:34:00Z');
  await worker.tick();
  assert.equal(sent, 2);
  assert.equal(reads, 3);
  assert.ok((await profiles.get(owner)).jobs.includes('2026-09-14:08:30'));
});
