import assert from 'node:assert/strict';
import { test } from 'node:test';
import { mkdtemp } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { PersonalMemory } from '../memory/store';
import { ProfileStore } from './profiles';
import { WorkService } from './work';
import { briefingText } from './cards';
const owner = { workspaceId: 'T1', userId: 'U1' };
const ref = { channelId: 'C1', threadTs: '1726000000.000001', workspaceHost: 'acme.slack.com' };
const source = { threadId: 'C1:1726000000.000001', messageId: '1726000000.000001', authorId: 'U1', text: 'I will send proposal Friday', sentAt: '2024-09-10T20:26:40.000Z', url: 'https://acme.slack.com/archives/C1/p1726000000000001' };
test('briefing uses selected evidence; failed access hides saved private work and reports stale status', async () => {
  const root = await mkdtemp(join(tmpdir(), 'intern-work-'));
  const profiles = new ProfileStore(join(root, 'profiles.json')), memory = new PersonalMemory(join(root, 'memory.json'));
  await profiles.configure(owner, 'Sales', ['Send proposal']);
  await profiles.select(owner, ref);
  await memory.apply(owner, { kind: 'commitment', title: 'Send proposal', deadline: { kind: 'unknown' }, evidence: [{ threadId: source.threadId, messageId: source.messageId, quote: source.text }] }, [source]);
  let denied = false;
  const access = { canRead: true, canDeliver: false, async readThread() { if (denied) throw new Error('missing_scope'); return [source]; } };
  const work = new WorkService(profiles, memory, access, async () => undefined);
  const fresh = await work.refresh(owner);
  assert.equal(fresh.memory.commitments.length, 1);
  assert.match(briefingText(fresh), /Send proposal/);
  denied = true;
  const stale = await work.refresh(owner);
  assert.equal(stale.memory.commitments.length, 0);
  assert.equal(stale.sources.length, 0);
  assert.equal(stale.reads[0].status, 'unavailable');
  assert.equal(stale.hiddenItems, 1);
  assert.match(briefingText(stale), /unavailable/i);
  await profiles.remove(owner, ref);
  const removed = await work.refresh(owner);
  assert.equal(removed.memory.commitments.length, 0);
});
test('overlapping manual/background owner jobs serialize but a failure does not poison later work', async () => {
  const root = await mkdtemp(join(tmpdir(), 'intern-work-'));
  const work = new WorkService(new ProfileStore(join(root, 'p.json')), new PersonalMemory(join(root, 'm.json')), { canRead: false, canDeliver: false, async readThread() { return []; } }, async () => undefined);
  const events: string[] = [];
  const one = work.exclusive(owner, async () => { events.push('start'); await Promise.resolve(); events.push('end'); throw new Error('failed'); });
  const two = work.exclusive(owner, async () => { events.push('next'); });
  await assert.rejects(one); await two;
  assert.deepEqual(events, ['start', 'end', 'next']);
});
